name: nyarios
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  settings_ui: ^2.0.2
  get_storage: ^2.1.1
  firebase_core: ^4.3.0
  url_launcher: ^6.1.12
  image_picker: ^1.0.0
  file_picker: ^10.3.8
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  firebase_auth: ^6.1.3
  google_sign_in: ^7.2.0
  uuid: ^4.5.2
  intl: ^0.20.2
  grouped_list: ^6.0.0
  dio: ^5.2.1+1
  path_provider: ^2.0.15
  material_floating_search_bar_2: ^0.5.0
  substring_highlight: ^1.0.33
  clipboard: ^3.0.10
  percent_indicator: ^4.2.3
  qr_flutter: ^4.1.0
  barcode_scan2: ^4.6.0
  share_plus: ^12.0.1
  agora_rtc_engine: ^6.2.2
  permission_handler: ^12.0.1
  http: ^1.6.0
  loading_animation_widget: ^1.2.0+4
  stop_watch_timer: ^3.0.1
  another_flushbar: ^1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
